### ISSUE TITLE
fk_TexModeがREPLACEの時にアルファ値が有効にならない

### ISSUE THREAD

**Issue by rita0222** [rita0222/FK#1]
以前は有効になっていたので、GL4対応時に挙動が変わったものと思われます。
この事象自体は仕様変更ということにしても良いですが、fk_SpriteModelが内部でRectTextureにREPLACEを設定しているため、アルファ値の制御を受け付けない状態になっており、これは何らかの対処を施した方が良いと思われます。

**Comment by earthwata** [comment]
了解です。私の環境 (Mac) だと fk_SpiteModel でもアルファ値は効いてるので、内部処理の問題というより fk_Model かどこかの設定値が以前と変更となったことが理由な気がします。

**Comment by rita0222** [comment]
テクスチャ自体のアルファ値(TextImageで文字描画した時など)は効くのですが、
私が手癖でよくやっていた
```
	spr.getMaterial()->setAlpha(0.5);
```
これがダメでした。
コードを見ると、REPLACEの時には `GLSL/Texture/FS_Replace` が使われており、このシェーダだとマテリアルの値を参照していないようなので、こうなるのは致し方ないです。

SpriteModelは画像にマテリアルの値を適用する使い方を想定しているので、MODULATEにするのが正しい対処かと思います。（現状はgetShape()したポインタをダウンキャスとして、モード変更することで回避しています）

**Comment by earthwata** [comment]
あー... 確かにそこは FK Ver.4 系列で仕様変更した点なんですよね。私が SpriteModel を利用するのは大半がテキスト表示だったので、自分の需要内では ForeColor と BackColor の設定だけで事足りてました。TextureMode を設定できる関数追加します。

**Comment by earthwata** [comment]
fk_SpriteModel に getTexture() と set|getTextureMode() 追加した版を master に push しました。

**Comment by rita0222** [comment]
対応ありがとうございました。確認したのでGitHubにも反映しました。
